
import '@/styles/base.scss';
import Header from '@/components/header'
import { AuthenticationProvider } from '@/providers/AuthenticationProvider';
import { use } from 'react';


export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <AuthenticationProvider >
            <html lang="en">
                <body>
                    <div className="wrapper">
                        <Header />
                        {children}
                    </div>
                </body>
            </html>
        </AuthenticationProvider>
    );
}
